### ISSUE TITLE
Roster bug 

### ISSUE THREAD

**Issue by kevaughnbailey** [antdroidx/CFB-Coach#34]
My team keep on requiring more players than plan 
Eg.  I have 3 wr out going senior and I redshirted 2 wr the previous draft,  I had no wr transferred but in the recruitment it said I needed 4 wr  when I should of right fully have 1 wr spot open for recruitment

**Comment by kevaughnbailey** [comment]
This also started to happen since the new updates.

**Comment by antdroidx** [comment]
I am looking at the code. It's funny because I updated every other position needs and WR was the only one of a couple that were correct. I'm fixing the recruiting issues for next update along with some other code cleanup. I'll keep looking at the WR thing though. Maybe this update will fix it.
