### ISSUE TITLE
Error in Game.java

### ISSUE THREAD

**Issue by dathomas1** [antdroidx/CFB-Coach#40]
I noticed the following error in the RushingPlay Post-Snap code

private void rushPlay(Team offense, Team defense, PlayerQB selQB, PlayerRB selRB, PlayerTE selTE, PlayerDL selDL, PlayerLB selLB, PlayerCB selCB, PlayerS selS) {
        boolean gotTD;
        gotTD = false;
        int yardsGain;
        int blockAdv = getCompositeOLRush(selTE) - getCompositeDLRush(selLB, selS) + (offense.**teamStratDef**.getRunProtection() - defense.teamStratDef.getRunProtection());
        int blockAdvOutside = selTE.ratRunBlock * 2 - selLB.ratRunStop - selS.ratRunStop + (offense.**teamStratDef**.getRunUsage() - defense.teamStratDef.getRunUsage());

Also, I noticed that some of the other parameters in Strategies aren't used in the Game code. Is there a reason they were taken out?

Finally, could you allow the Recruits to be sorted by cost? Or the copy the filtering capabilities of Hoops Coach?

And thanks for the time and effort of developing this massive mod!

**Comment by antdroidx** [comment]
Thanks. This will be implemented in next update.

**Comment by antdroidx** [comment]
fixed in v1.1.8

i think there was a couple ideas i had for the parameters but i never implemented it because i didnt need to at the time. i have to check back at my notebook to see what the idea was again.

recruit filtering will be in v1.1.10 or .11
