### ISSUE TITLE
Game crashes after recruiting with custom universe

### ISSUE THREAD

**Issue by quetzle** [antdroidx/CFB-Coach#50]
After the first recruiting, my game crashes.

Using the custom universe spreadsheet, the default values work just fine: https://pastebin.com/raw/Y265beAQ

However, after changing the names of 12 teams and the names of the conferences, the game crashes after recruiting: https://pastebin.com/raw/yRwKf81J

I have a fully edited universe that I replaced parts of with the working universe to create the one above. I've been unable to figure out what causes the crash. Changing the conference names on the working universe didn't crash it, and editing single colleges' names didn't either.

**Comment by antdroidx** [comment]
I don't know exactly why yet but from debugging, the "VISA" team is crashing the game on load.

**Comment by quetzle** [comment]
That is very strange lol
