### ISSUE TITLE
Custom Game Crashing

### ISSUE THREAD

**Issue by CodyAHurley** [antdroidx/CFB-Coach#58]
So I followed your directions to a T and when I try to open the game with my custom universe it crashes and I have no idea why. Is there anyway you can please help me? I spent hours trying to get this to work.
[cfc universe setup v2-1_Clean.txt](https://github.com/antdroidx/CFB-Coach/files/2626025/cfc.universe.setup.v2-1_Clean.txt)

**Comment by antdroidx** [comment]
I believe this was already resolved. If it has not, please email me @ contact@antdroid.net
